// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKu8kO7NQ339qSDpQ29g8EjFuH5RdK8IA',
    appId: '1:215192033123:android:67011b51c3008e11baa556',
    messagingSenderId: '215192033123',
    projectId: 'mening-kutubxonam-c8083',
    databaseURL: 'https://mening-kutubxonam-c8083-default-rtdb.firebaseio.com',
    storageBucket: 'mening-kutubxonam-c8083.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQlu3al7qYBEhajgGohPglqeCePPT4_s8',
    appId: '1:215192033123:ios:e98dcdc220777b00baa556',
    messagingSenderId: '215192033123',
    projectId: 'mening-kutubxonam-c8083',
    databaseURL: 'https://mening-kutubxonam-c8083-default-rtdb.firebaseio.com',
    storageBucket: 'mening-kutubxonam-c8083.firebasestorage.app',
    iosBundleId: 'com.example.meningKutubxonam',
  );
}
